name: examples/bad-set linting

on:
    push:
        branches:
          - main
    pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: running_linter
        uses: calyptia/fluent-linter-action@main
        with:
          CALYPTIA_API_KEY: ${{ secrets.CALYPTIA_API_KEY }}
          CONFIG_LOCATION_GLOB: 'examples/bad-set/fluent-bit.conf'
